### ISSUE TITLE
Not enough memes

### ISSUE THREAD

**Issue by vingkan** [steinomatic/steinomatic.github.io#1]
I really expected more

**Comment by bbatliner** [comment]
+1

**Comment by vingkan** [comment]
Some pepes would be great

**Comment by vingkan** [comment]
![image](https://cloud.githubusercontent.com/assets/11896652/11523066/1c4f584c-9884-11e5-8a50-576c1c9f6799.png)

**Comment by bbatliner** [comment]
I, for one, welcome our new president.
![image](https://cloud.githubusercontent.com/assets/5896658/11523065/1992326e-9884-11e5-8914-840a2fe7dac2.png)
